config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"

   resources :examinations

   get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index', as: 'quiz_mc_questions' # nested index
   get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new', as: 'new_quiz_mc_question' # nested new
   post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create' # nested create
   #get 'mc_questions', to: 'mc_questions#index', as: 'mc_questions' # index
   #get 'mc_questions/new', to: 'mc_questions#new', as: 'new_mc_question' # new
   get 'mc_questions/:id', to: 'mc_questions#show', as: 'mc_question' # show
   #post 'mc_questions', to: 'mc_questions#create' # create
   get 'mc_questions/:id/edit', to: 'mc_questions#edit', as: 'edit_mc_question' # edit
   patch 'mc_questions/:id', to: 'mc_questions#update' # update (as needed)
   put 'mc_questions/:id', to: 'mc_questions#update' # update (full replacement)
   delete 'mc_questions/:id', to: 'mc_questions#destroy' # destroy
   

   get 'quizzes', to: 'quizzes#index', as: 'quizzes' # index
   get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz' # new
   post 'quizzes', to: 'quizzes#create' # create
   delete 'quizzes/:id', to: 'quizzes#destroy' # destroy
   get 'quizzes/:id', to: 'quizzes#show', as: 'quiz' # show
   get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz' # edit
   put 'quizzes/:id', to: 'quizzes#update' # update (put)
   patch 'quizzes/:id', to: 'quizzes#update' # update (patch)
   
   
   
   
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

    def index
        # get all quiz objects
        quizzes = Quiz.all
        # display index view
        respond_to do |format|
          format.html { render :index, locals: { quizzes: quizzes } }
        end
      end

      def new
        # make empty quiz object
        quiz = Quiz.new
        # display new view
        respond_to do |format|
          format.html { render :new, locals: { quiz: quiz } }
        end
      end
      
      def create
        # new object from params
        quiz = Quiz.new(params.require(:quiz).permit(:title, :description))
        # respond_to block
        respond_to do |format|
          format.html do
            if quiz.save
              # success message
              flash[:success] = "Quiz saved successfully"
              # redirect to index
              redirect_to quizzes_url
            else
              # error message
              flash.now[:error] = "Error: Quiz could not be saved"
              # render new
              render :new, locals: { quiz: quiz }
            end
          end
        end
      end

      def show
        # find a particular object
        quiz = Quiz.find(params[:id])
        # display the object
        respond_to do |format|
          format.html { render :show, locals: { quiz: quiz } }
        end
      end

      

      def edit
        # object to use in form
        quiz = Quiz.find(params[:id])
        respond_to do |format|
          format.html { render :edit, locals: { quiz: quiz } }
        end
      end
      
      def update
        # load existing object again from URL param
        quiz = Quiz.find(params[:id])
        # respond_to block
        respond_to do |format|
          format.html do
            if quiz.update(params.require(:quiz).permit(:title, :description))
              # success message
              flash[:success] = 'Quiz updated successfully'
              # redirect to index
              redirect_to quizzes_url
            else
              # error message
              flash.now[:error] = 'Error: Quiz could not be updated'
              # render edit
              render :edit, locals: { quiz: quiz }
            end
          end
        end
      end

      def destroy
        # load existing object again from URL param
        quiz = Quiz.find(params[:id])
        # destroy object
        quiz.destroy
        # respond_to block
        respond_to do |format|
          format.html do
            # success message
            flash[:success] = 'Quiz removed successfully'
            # redirect to index
            redirect_to quizzes_url
          end
        end
      end


end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/edit.html.erb
<h1>Edit Quiz</h1>

<%= form_with model: quiz, url: quiz_path, method: :patch, local: true, scope: :quiz do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: "27x7" %>
  </div>

  <%= form.submit "Update Quiz" %>

<% end %>

app/views/quizzes/index.html.erb
<h1>Quizzes</h1>
<%= link_to 'New Quiz', new_quiz_path %>



<% quizzes.each do |quiz| %>
  <div id="<%= dom_id(quiz) %>">
    <br>
    <p>
      <%= quiz.title %>
      <%= link_to '🔎', quiz_path(quiz) %>
      <%= link_to '🖋', edit_quiz_path(quiz) %>
    </p>
    <p>
      <%= truncate quiz.description, length: 75, separator: ' ' %>
    </p>
  </div>
  <%= button_to 'Delete', quiz_path(quiz), method: :delete %>
<% end %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= form_with model: quiz, url: quizzes_path, method: :post, local: true, scope: :quiz do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: "27x7" %>
  </div>

  <%= form.submit "Add Quiz" %>

<% end %>

app/views/quizzes/show.html.erb
<h1><%= quiz.title %></h1>

<p>
  <%= quiz.description %>
</p>
<%= button_to 'Delete', quiz_path(quiz), method: :delete %>

<h2>Questions</h2>

<%= button_to 'New Question', new_quiz_mc_question_path(quiz) %>

<% quiz.mc_questions.each do |question| %>
  <div id="<%= dom_id(question) %>">
    <p>
      <%= question.question %>
      <%= link_to '🔎', mc_question_path(question) %>
      <%= link_to '🖋', edit_mc_question_path(question) %>
      <%= button_to '🗑', mc_question_path(question), method: :delete %>
    </p>

    <%
      choices = [question.answer, question.distractor_1]
      choices << question.distractor_2 if !question.distractor_2.blank?
      choices.each do |c|
    %>
      <div>
        <%= radio_button_tag "guess_#{question.id}", c, checked = c == question.answer, disabled: true %>
        <%= label_tag "guess_#{question.id}_#{c}", c %>
      </div>
    <% end %>
  </div>
<% end %>