config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"

   resources :examinations

   get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index', as: 'quiz_mc_questions' # nested index
   get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new', as: 'new_quiz_mc_question' # nested new
   post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create' # nested create
   #get 'mc_questions', to: 'mc_questions#index', as: 'mc_questions' # index
   #get 'mc_questions/new', to: 'mc_questions#new', as: 'new_mc_question' # new
   get 'mc_questions/:id', to: 'mc_questions#show', as: 'mc_question' # show
   #post 'mc_questions', to: 'mc_questions#create' # create
   get 'mc_questions/:id/edit', to: 'mc_questions#edit', as: 'edit_mc_question' # edit
   patch 'mc_questions/:id', to: 'mc_questions#update' # update (as needed)
   put 'mc_questions/:id', to: 'mc_questions#update' # update (full replacement)
   delete 'mc_questions/:id', to: 'mc_questions#destroy' # destroy
   

   get 'quizzes', to: 'quizzes#index', as: 'quizzes' # index
   get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz' # new
   post 'quizzes', to: 'quizzes#create' # create
   delete 'quizzes/:id', to: 'quizzes#destroy' # destroy
   get 'quizzes/:id', to: 'quizzes#show', as: 'quiz' # show
   get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz' # edit
   put 'quizzes/:id', to: 'quizzes#update' # update (put)
   patch 'quizzes/:id', to: 'quizzes#update' # update (patch)
   
   
   
   
end

app/controllers/quiz_mc_questions_controller.rb
class QuizMcQuestionsController < ApplicationController

    def index
        quiz = Quiz.includes(:mc_questions).find(params[:id])
        respond_to do |format|
          format.html { render :index, locals: { quiz: quiz, questions: quiz.mc_questions } }
        end
      end

      def new
        quiz = Quiz.find(params[:id])
        respond_to do |format|
          format.html { render :new, locals: { quiz: quiz, question: quiz.mc_questions.build } }
        end
      end

      def create
        # find the quiz to which the new question will be added
        quiz = Quiz.find(params[:id])
        # allocate a new question associated with the quiz
        question = quiz.mc_questions.build(params.require(:mc_question).permit(:question, :answer, :distractor_1, :distractor_2))
        # respond_to block
        respond_to do |format|
          format.html do
            if question.save
              # success message
              flash[:success] = "Question saved successfully"
              # redirect to index
              redirect_to quiz_mc_questions_url(quiz)
            else
              # error message
              flash.now[:error] = "Error: Question could not be saved"
              # render new
              render :new, locals: { quiz: quiz, question: question }
            end
          end
        end
      end



end

app/helpers/quiz_mc_questions_helper.rb
module QuizMcQuestionsHelper
end

app/views/quiz_mc_questions/index.html.erb
<h1>Multiple-Choice Questions</h1>

<%= link_to 'New Question', new_quiz_mc_question_path(quiz) %>
<% questions.each do |question| %>
    <div id="<%= dom_id(question) %>">
        <p>
            <%= question.question %>
            <%= link_to '🔎', mc_question_path(question) %>
            <%= link_to '🖋', edit_mc_question_path(question) %>
            <%= link_to '🗑', mc_question_path(question), method: :delete %>
        </p>
        <% choices = [question.answer, question.distractor_1, question.distractor_2] %>
        <% choices.each do |c| %>
            <div>
                <%= radio_button_tag "guess_#{question.id}", c, checked = c == question.answer, disabled: true %>
                <%= label_tag "guess_#{question.id}_#{c}", c %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/quiz_mc_questions/new.html.erb
<h1>New Question</h1>

<%= form_with model: question, url: quiz_mc_questions_path(quiz), method: :post, local: true, scope: :mc_question do |f| %>

  <div>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>

  <div>
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>

  <div>
    <%= f.label :distractor_1 %><br>
    <%= f.text_field :distractor_1 %>
  </div>

  <div>
    <%= f.label :distractor_2 %><br>
    <%= f.text_field :distractor_2 %>
  </div>

  <%= f.submit "Add Question" %>
<% end %>