config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"

   resources :examinations

   get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index', as: 'quiz_mc_questions' # nested index
   get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new', as: 'new_quiz_mc_question' # nested new
   post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create' # nested create
   #get 'mc_questions', to: 'mc_questions#index', as: 'mc_questions' # index
   #get 'mc_questions/new', to: 'mc_questions#new', as: 'new_mc_question' # new
   get 'mc_questions/:id', to: 'mc_questions#show', as: 'mc_question' # show
   #post 'mc_questions', to: 'mc_questions#create' # create
   get 'mc_questions/:id/edit', to: 'mc_questions#edit', as: 'edit_mc_question' # edit
   patch 'mc_questions/:id', to: 'mc_questions#update' # update (as needed)
   put 'mc_questions/:id', to: 'mc_questions#update' # update (full replacement)
   delete 'mc_questions/:id', to: 'mc_questions#destroy' # destroy
   

   get 'quizzes', to: 'quizzes#index', as: 'quizzes' # index
   get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz' # new
   post 'quizzes', to: 'quizzes#create' # create
   delete 'quizzes/:id', to: 'quizzes#destroy' # destroy
   get 'quizzes/:id', to: 'quizzes#show', as: 'quiz' # show
   get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz' # edit
   put 'quizzes/:id', to: 'quizzes#update' # update (put)
   patch 'quizzes/:id', to: 'quizzes#update' # update (patch)
   
   
   
   
end

app/models/mc_question.rb
# == Schema Information
#
# Table name: mc_questions
#
#  id           :integer          not null, primary key
#  answer       :string
#  distractor_1 :string
#  distractor_2 :string
#  question     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  quiz_id      :integer
#
# Indexes
#
#  index_mc_questions_on_quiz_id  (quiz_id)
#
# Foreign Keys
#
#  quiz_id  (quiz_id => quizzes.id)
#
class McQuestion < ApplicationRecord
end

app/controllers/mc_questions_controller.rb
class McQuestionsController < ApplicationController


     def show
            question = McQuestion.find(params[:id])
            respond_to do |format|
               format.html { render :show, locals: { question: question } }
            end
        end

      

    def edit
        question = McQuestion.find(params[:id])
        respond_to do |format|
          format.html { render :edit, locals: { question: question } }
        end
      end

      def update
        question = McQuestion.find(params[:id])
        respond_to do |format|
          format.html do
            if question.update(params.require(:mc_question).permit(:question, :answer, :distractor_1, :distractor_2))
              flash[:success] = 'Question updated successfully'
              redirect_to quiz_questions_url

            else
              flash.now[:error] = 'Error: Question could not be updated'
              render :edit, locals: { question: question }

            end
          end
      end
    end

       def destroy
        question = McQuestion.find(params[:id])
        question.destroy
          respond_to do |format|
             format.html do
             flash[:success] = 'Question removed successfully'
             redirect_to quiz_questions_url
        end
      end
    end

end

app/helpers/mc_questions_helper.rb
module McQuestionsHelper
end

app/views/mc_questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_with model: question, url: mc_question_path, method: :patch, local: true, scope: :mc_question do |f| %>

  <div>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>

  <div>
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>

  <div>
    <%= f.label :distractor_1 %><br>
    <%= f.text_field :distractor_1 %>
  </div>

  <div>
    <%= f.label :distractor_2 %><br>
    <%= f.text_field :distractor_2 %>
  </div>

  <%= f.submit 'Update Question' %>

<% end %>

app/views/mc_questions/index.html.erb
<%= link_to 'New Question', new_mc_question_path %>
<% questions.each do |question| %>
    <div id="<%= dom_id(question) %>">
        <p><%= question.question %></p>
        <% choices = [question.answer, question.distractor_1, question.distractor_2] %>
        <% choices.each do |c| %>
            <div>
                <%= radio_button_tag "guess_#{question.id}", c, checked = c == question.answer, disabled: true %>
                <%= label_tag "guess_#{question.id}_#{c}", c %>
            </div>

        <% end %>
        <%= link_to 'Show', mc_question_path(question) %>
        <%= link_to 'Edit', edit_mc_question_path(question) %>
        <%= button_to 'Delete', mc_question_path(question), method: :delete %>
        
        
    </div>
    
<% end %>

app/views/mc_questions/show.html.erb
<p><%= question.question %></p>
<%= link_to 'Edit', edit_mc_question_path(question) %>
<% choices = [question.answer, question.distractor_1, question.distractor_2] %>
<% choices.each do |c| %>
    <div>
        <%= radio_button_tag "guess", c, checked = c == question.answer, disabled: true %>
        <%= label_tag "guess_#{c}", c %>
    </div>
    
<% end %>
<%= button_to 'Delete', mc_question_path(question), method: :delete %>