config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"

   resources :examinations

   get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index', as: 'quiz_mc_questions' # nested index
   get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new', as: 'new_quiz_mc_question' # nested new
   post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create' # nested create
   #get 'mc_questions', to: 'mc_questions#index', as: 'mc_questions' # index
   #get 'mc_questions/new', to: 'mc_questions#new', as: 'new_mc_question' # new
   get 'mc_questions/:id', to: 'mc_questions#show', as: 'mc_question' # show
   #post 'mc_questions', to: 'mc_questions#create' # create
   get 'mc_questions/:id/edit', to: 'mc_questions#edit', as: 'edit_mc_question' # edit
   patch 'mc_questions/:id', to: 'mc_questions#update' # update (as needed)
   put 'mc_questions/:id', to: 'mc_questions#update' # update (full replacement)
   delete 'mc_questions/:id', to: 'mc_questions#destroy' # destroy
   

   get 'quizzes', to: 'quizzes#index', as: 'quizzes' # index
   get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz' # new
   post 'quizzes', to: 'quizzes#create' # create
   delete 'quizzes/:id', to: 'quizzes#destroy' # destroy
   get 'quizzes/:id', to: 'quizzes#show', as: 'quiz' # show
   get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz' # edit
   put 'quizzes/:id', to: 'quizzes#update' # update (put)
   patch 'quizzes/:id', to: 'quizzes#update' # update (patch)
   
   
   
   
end

app/models/examination.rb
# == Schema Information
#
# Table name: examinations
#
#  id            :integer          not null, primary key
#  college_name  :string
#  department    :string
#  email         :string
#  full_name     :string
#  mobile_number :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Examination < ApplicationRecord
    validates :full_name, :email, :department, :college_name, :mobile_number, presence: true
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
   

    def index
        @examinations = Examination.all
    end

    def new
        @examination = Examination.new
    end

    def create
        @examination = Examination.new(examination_params)
        if @examination.save
            redirect_to examinations_path
        else
            render :new
        end
    end

    private

    def examination_params
        params.require(:examination).permit(:full_name, :email, :department, :college_name, :mobile_number)
    end

   

end

app/views/examinations/index.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Register For Exam', new_examination_path %>

<%= button_to 'Log out', destroy_user_session_path, method: :delete %>

<h1>List Of Participation</h1>

<table>
<thead>
<tr>
<th>Students Name</th>
<th>College</th>
</tr>
</thead>
<tbody>
<% @examinations.each do |examination| %>
    <tr>
      <td><%= examination.full_name %></td>
      <td><%= examination.college_name %></td>
      </tr>
      <% end %>
      </tbody>
      </table>

app/views/examinations/new.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Participation', examinations_path %>

<%= button_to 'Log out', destroy_user_session_path, method: :delete %>
<h1>Register For Exam Here</h1>


<%= form_with model: @examination do |form| %>

    <% if @examination.errors.any? %>
      <% @examination.errors.full_messages.each do |message| %>
        <p><%= message %></p>
        <% end %>
    <% end %>

    <div>
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name %>
    </div>

    <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
    </div>

    <div>
    <%= form.label :department %><br>
    <%= form.text_field :department %>
    </div>

    <div>
    <%= form.label :college_name %><br>
    <%= form.text_field :college_name %>
    </div>

    <div>
    <%= form.label :mobile_number %><br>
    <%= form.text_field :mobile_number %>
    </div>
  
    <br>
    <div>
    <%= form.submit :Submit %>
    </div>


    <% end %>